### PR TITLE
Andrew/add tests 283

### PR DESCRIPTION
**Pull request by YeahNotSewerSide**
https://github.com/vechain/protocol-board-repo/issues/283

### CODE REVIEW

**Comment by YeahNotSewerSide** [comment]
waiting for this pull request to be merged https://github.com/vechain/thor/pull/813

**Comment by YeahNotSewerSide** [comment]
> @YeahNotSewerSide could you take another look at this please.

waiting for this version o become the latest docker image [https://hub.docker.com/layers/vechain/thor/v2.1.4-rc.1/images/sha256-812f7e137d08a9a[…]5ddc9cd8d6033e65dcde6e59c050bd0d2339f29654240?context=explore](https://hub.docker.com/layers/vechain/thor/v2.1.4-rc.1/images/sha256-812f7e137d08a9afe7b5ddc9cd8d6033e65dcde6e59c050bd0d2339f29654240?context=explore)

**Comment by darrenvechain** [comment]
@YeahNotSewerSide looks like we have a failure, is it expected?
```
  ❌ should get non empty storage, empty maxResult
	Error: expect(received).toBeString()
```

**Comment by YeahNotSewerSide** [comment]
> @YeahNotSewerSide looks like we have a failure, is it expected?
> 
> ```
>   ❌ should get non empty storage, empty maxResult
> 	Error: expect(received).toBeString()
> ```

Yes, I was expecting a key there, I discussed it with @libotony, changed to toBeNull

**Review by darrenvechain — APPROVED** [review]

**Pull request merged**
