### PR TITLE
Add beat test

### PR DESCRIPTION
**Pull request by paologalligit**
This refers to this [issue](https://github.com/vechain/protocol-board-repo/issues/277).

### CODE REVIEW

**Comment by darrenvechain** [comment]
Hey @paologalligit would it be possible to add some bloom tests?

If we perform some transactions and check for the addresses in the bloom filter, expected output is true.

Seem `bloom.ts` https://github.com/vechain/thor-e2e-tests/blob/main/src/utils/bloom.ts

**Comment by darrenvechain** [comment]
> Hey @paologalligit would it be possible to add some bloom tests?
> 
> If we perform some transactions and check for the addresses in the bloom filter, expected output is true.
> 
> Seem `bloom.ts` https://github.com/vechain/thor-e2e-tests/blob/main/src/utils/bloom.ts

See also https://github.com/vechain/thor-e2e-tests/blob/main/test/thorest-api/subscriptions/ws-beat2.test.ts

**Comment by leszek-vechain** [comment]
that would be useful too ^ do we have any bloom check in thor ? just to not duplicate tests

**Comment by darrenvechain** [comment]
> that would be useful too ^ do we have any bloom check in thor ? just to not duplicate tests

e2e is useful here IMO

**Comment by paologalligit** [comment]
> just a quick q - do we check linting before commits ?

At the moment we are not, here is a ticket to introduce the linter in the github actions

**Review by leszek-vechain — APPROVED** [review]
@darrenvechain can you have a look ? if we need more bloom checks

**Pull request merged**
